import { JetBrains_Mono } from "next/font/google";
import "./globals.css";

// import here components
import Header from "@/components/Header";

const JetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-JetbrainsMono",
});

export const metadata = {
  title: "Encton",
  description: "Generated by Gaurav Tiwari",
};

const layout = ({ children }) => {
  return (
    <html lang="en">
      <body className={JetbrainsMono.variable}>
        <Header />

        {children}
      </body>
    </html>
  );
};

export default layout;
